### ISSUE TITLE
来源请求

### ISSUE THREAD

**Issue by simon300000** [nakaharalin/hololive-720#1]
可以给每个文件夹加一个md，然后稍稍注明一下介绍和来源什么的？

**Comment by simon300000** [comment]
然后就可以上github pages直接分发了

**Comment by nakaharalin** [comment]
嗯，等这边讨论完会着手的

**Comment by nakaharalin** [comment]
> 可以给每个文件夹加一个md，然后稍稍注明一下介绍和来源什么的？

等这边讨论完会着手进行的

**Comment by simon300000** [comment]
> > 可以给每个文件夹加一个md，然后稍稍注明一下介绍和来源什么的？
> 
> 等这边讨论完会着手进行的

辛苦了
