### ISSUE TITLE
希望将这两个视频添加进证据，更加可信

### ISSUE THREAD

**Issue by SekiBetu** [nakaharalin/hololive-720#4]
http://vc.bilibili.com/mobile/detail?vc=2362330&bilifrom=1

https://www.bilibili.com/video/av59813014

**Comment by yttrium3** [comment]
第一个已经有了

**Comment by nakaharalin** [comment]
> http://vc.bilibili.com/mobile/detail?vc=2362330&bilifrom=1
> 
> https://www.bilibili.com/video/av59813014

已添加
