### ISSUE TITLE
[功能请求]Github pages

### ISSUE THREAD

**Issue by ghost** [nakaharalin/hololive-720#5]
https://pages.github.com/

**Comment by simon300000** [comment]
@studentmain 如果需要的话，我可以提供一个vtbs.moe的二级域名（

**Comment by PoiScript** [comment]
新建一个 gh-pages 的 branch 即可... 会部署到域名 https://nakaharalin.github.io/hololive-720 上

**Comment by simon300000** [comment]
我记得是需要到Setting里打开github pages功能
而且这个repo主要就是markdown，完全可以直接在master分支上部署
之后可以加CNAME什么的

**Comment by PoiScript** [comment]
直接用 master 分支也行 加个 jekyll 配置文件就行了

**Comment by simon300000** [comment]
个人感觉这个jekyll都不需要

**Comment by PoiScript** [comment]
github pages 自带 jekyll 的.. 你把配置文件一放人家自动生成好 html... 不然你让人家人脑解析 markdown 么

**Comment by ghost** [comment]
点一下自然会生成该有的配置文件的。倒是的确不用手写。

**Comment by simon300000** [comment]
整了一个hololive-720.vtbs.moe
可以直接CNAME了@nakaharalin

**Comment by ghost** [comment]
由于功能已实现，关闭此issue
