### ISSUE TITLE
readme图片因为目录结构改动都挂了

### ISSUE THREAD

**Issue by SekiBetu** [nakaharalin/hololive-720#8]
![image](https://user-images.githubusercontent.com/38283893/61580498-82610400-ab45-11e9-8565-60f2c7540a35.png)

**Comment by Kotoki1337** [comment]
在修了

**Comment by simon300000** [comment]
草
修重了

**Comment by Kotoki1337** [comment]
> 草
> 修重了

呆了，咱们俩同时修然后同时串库
![)QAX946TGAMF6$TS62Y5PVY](https://user-images.githubusercontent.com/35394151/61580722-7fffa980-ab47-11e9-8d8b-55ddee4edccc.png)

**Comment by simon300000** [comment]
> > 草
> > 修重了
> 
> 呆了，咱们俩同时修然后同时串库
> ![)QAX946TGAMF6$TS62Y5PVY](https://user-images.githubusercontent.com/35394151/61580722-7fffa980-ab47-11e9-8d8b-55ddee4edccc.png)

那我先出去买东西吃了233
